version: '3.8'

services:
  vaspbot:
    build: .
    container_name: vaspbot
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      # Isse aapki memory files AWS server par permanent rahengi
      - ../SOUL.md:/SOUL.md
      - ../MEMORY.md:/MEMORY.md
      - ../memory_legacy:/memory_legacy
